/**
 * placeOrder transaction factory
 * 注文取引ファクトリー
 * @namespace transaction.placeOrder
 */

import * as GMO from '@motionpicture/gmo-service';
import * as waiter from '@motionpicture/waiter-domain';

import { IAction as IAuthorizeAction } from '../action/authorize';
import { IExtendId } from '../autoGenerated';
import { IOrder } from '../order';
import OrganizationType from '../organizationType';
import PaymentMethodType from '../paymentMethodType';
import { IContact, IPerson } from '../person';
import PersonType from '../personType';
import * as EventReservationFactory from '../reservation/event';
import * as TransactionFactory from '../transaction';
import TransactionStatusType from '../transactionStatusType';
import TransactionTasksExportationStatus from '../transactionTasksExportationStatus';
import TransactionType from '../transactionType';

/**
 * クレジットカード売上結果
 */
export type ICreditCardSales = GMO.services.credit.IAlterTranResult;

/**
 * customer contact interface
 * 購入者連作先インターフェース
 * @export
 * @interface
 * @memberof transaction.placeOrder
 */
export type ICustomerContact = IContact;

/**
 * seller interface
 * 販売者インターフェース
 * @export
 * @interface
 * @memberof transaction.placeOrder
 */
export interface ISeller {
    typeOf: OrganizationType | PersonType;
    id: string;
    name: string;
    url?: string;
}

/**
 * agent interface
 * 購入者インターフェース
 * @export
 * @interface
 * @memberof transaction.placeOrder
 */
export type IAgent = IPerson;

/**
 * result interface
 * 取引結果インターフェース
 * @export
 * @interface
 * @memberof transaction.placeOrder
 */
// tslint:disable-next-line:no-empty-interface
export interface IResult {
    /**
     * 注文データ
     */
    order: IOrder;
    /**
     * GMO売上結果
     */
    creditCardSales?: ICreditCardSales;
    /**
     * 座席予約リスト
     */
    eventReservations: EventReservationFactory.IReservation[];
}

/**
 * error interface
 * エラーインターフェース
 * @export
 * @interface
 * @memberof transaction.placeOrder
 */
export type IError = any;

/**
 * object of a transaction interface
 * 取引対象物インターフェース
 * @export
 * @interface
 * @memberof transaction.placeOrder
 */
export interface IObject {
    // tslint:disable-next-line:no-suspicious-comment
    /**
     * WAITER許可証トークン
     * TODO 必須プロパティに変更
     */
    passportToken?: waiter.factory.passport.IEncodedPassport;
    // tslint:disable-next-line:no-suspicious-comment
    /**
     * WAITER許可証
     * TODO 必須プロパティに変更
     */
    passport?: waiter.factory.passport.IPassport;
    /**
     * 購入者区分
     */
    purchaser_group: string;
    /**
     * customer contact
     */
    customerContact?: ICustomerContact;
    /**
     * 認可アクションリスト
     */
    authorizeActions: IAuthorizeAction[];
    /**
     * 決済方法
     */
    paymentMethod?: PaymentMethodType;
}

export type ITransaction = IExtendId<IAttributes>;

/**
 * place order transaction interface
 * 注文取引インターフェース
 * @export
 * @interface
 * @memberof transaction.placeOrder
 */
export interface IAttributes extends TransactionFactory.IAttributes {
    /**
     * 購入者
     */
    agent: IAgent;
    /**
     * 販売者
     */
    seller: ISeller;
    /**
     * 取引の結果発生するもの
     */
    result?: IResult;
    /**
     * 取引に関するエラー
     */
    error?: IError;
    /**
     * 取引の対象物
     * 座席仮予約、クレジットカードのオーソリなど、取引を構成する承認などが含まれます。
     */
    object: IObject;
}

/**
 * create placeOrderTransaction object.
 * 注文取引オブジェクトを生成する。
 * @export
 * @function
 * @memberof transaction.placeOrder
 */
export function createAttributes(params: {
    status: TransactionStatusType;
    agent: IAgent
    seller: ISeller;
    result?: IResult;
    error?: IError;
    object: IObject;
    expires: Date;
    startDate?: Date;
    endDate?: Date;
    tasksExportedAt?: Date;
    tasksExportationStatus: TransactionTasksExportationStatus;
}): IAttributes {
    return {
        ...TransactionFactory.createAttributes({
            typeOf: TransactionType.PlaceOrder,
            status: params.status,
            agent: params.agent,
            result: params.result,
            error: params.error,
            object: params.object,
            expires: params.expires,
            startDate: params.startDate,
            endDate: params.endDate,
            tasksExportedAt: params.tasksExportedAt,
            tasksExportationStatus: params.tasksExportationStatus
        }),
        ...{
            seller: params.seller,
            object: params.object
        }
    };
}
