import * as cinerino from '@cinerino/factory';
import * as GMO from '@motionpicture/gmo-service';

import { IExtendId } from '../autoGenerated';

/**
 * クレジットカード売上取消結果インターフェース
 */
export type IReturnCreditCardResult = GMO.services.credit.IAlterTranResult;
/**
 * クレジットカード金額変更結果インターフェース
 */
export type IChangeCreditCardAmountResult = GMO.services.credit.IChangeTranResult;

export import IAgent = cinerino.transaction.returnOrder.IAgent;

/**
 * result interface
 * 取引結果インターフェース
 */
export interface IResult {
    returnCreditCardResult?: IReturnCreditCardResult;
    changeCreditCardAmountResult?: IChangeCreditCardAmountResult;
}

/**
 * error interface
 * エラーインターフェース
 */
export type IError = any;

/**
 * 返品理由
 */
export import Reason = cinerino.transaction.returnOrder.Reason;

/**
 * object of a transaction interface
 * 取引対象物インターフェース
 */
export interface IObject extends cinerino.transaction.returnOrder.IObject {
    transaction: cinerino.transaction.ITransaction<cinerino.transactionType.PlaceOrder>;
    cancelName: string;
}

export import IPotentialActionsParams = cinerino.transaction.returnOrder.IPotentialActionsParams;

export interface IPotentialActions {
    /**
     * 注文返品アクション属性
     */
    returnOrder: cinerino.action.transfer.returnAction.order.IAttributes;
}

export type ITransaction = IExtendId<IAttributes>;

/**
 * 返品取引インターフェース
 */
export interface IAttributes extends cinerino.transaction.IAttributes<cinerino.transactionType.ReturnOrder> {
    /**
     * 取引の結果発生するもの
     */
    result?: IResult;
    /**
     * 取引の対象物
     */
    object: IObject;
    potentialActions?: IPotentialActions;
}

export type ISearchConditions = cinerino.transaction.ISearchConditions<cinerino.transactionType.ReturnOrder>;
