import * as cinerino from '@cinerino/factory';

import { IExtendId } from '../autoGenerated';
import TaskName from '../taskName';

export interface IData {
    /**
     * イベントID
     */
    id: string;
}

export interface IAttributes extends cinerino.task.IAttributes<TaskName.AggregateEventReservations> {
    data: IData;
}

/**
 * イベント予約集計タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
