import * as cinerino from '@cinerino/factory';

import { IExtendId } from '../autoGenerated';
import TaskName from '../taskName';

export interface IData {
    transactionId: string;
}

export interface IAttributes extends cinerino.task.IAttributes<TaskName.CancelSeatReservation> {
    data: IData;
}

export type ITask = IExtendId<IAttributes>;
