import * as cinerino from '@cinerino/factory';

import { IExtendId } from '../autoGenerated';
import TaskName from '../taskName';
import { ITransaction } from '../transaction/returnOrder';

export interface IData {
    transaction: ITransaction;
}

export interface IAttributes extends cinerino.task.IAttributes<TaskName.CreateReturnOrderReport> {
    data: IData;
}

/**
 * 注文返品取引レポート作成タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
