import * as cinerino from '@cinerino/factory';

import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

export interface IData {
    transaction: cinerino.transaction.ITransaction<cinerino.transactionType.PlaceOrder>;
}

export interface IAttributes extends TaskFactory.IAttributes<TaskName.CreatePlaceOrderReport> {
    data: IData;
}

/**
 * 注文取引レポート作成タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
