import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import TaskName from '../taskName';
import { ITransaction } from '../transaction/returnOrder';

export interface IData {
    transaction: ITransaction;
}

export interface IAttributes extends TaskFactory.IAttributes<TaskName.CreateReturnOrderReport> {
    data: IData;
}

/**
 * 注文返品取引レポート作成タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
