import * as cinerino from '@cinerino/factory';

import { IExtendId } from '../autoGenerated';
import TaskName from '../taskName';

export type IData = any;

export interface IAttributes extends cinerino.task.IAttributes<TaskName.ImportEvent> {
    data: IData;
}

export type ITask = IExtendId<IAttributes>;
