import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

export interface IData {
    /**
     * 返品アクションを起こした主体ID
     */
    agentId: string;
    /**
     * 返品対象のパフォーマンスID
     */
    performanceId: string;
    /**
     * 返品対象の注文クライアントID
     */
    clientIds: string[];
}

export interface IAttributes extends TaskFactory.IAttributes<TaskName.ReturnOrdersByPerformance> {
    data: IData;
}

export type ITask = IExtendId<IAttributes>;
