import * as cinerino from '@cinerino/factory';

import { IExtendId } from '../autoGenerated';
import TaskName from '../taskName';

export interface IData {
    /**
     * Cinerino API認証情報
     */
    credentials: {
        /**
         * リフレッシュトークン
         */
        refresh_token?: string;
        /**
         * アクセストークン
         */
        access_token?: string;
    };
    /**
     * 返品アクションを起こした主体ID
     */
    agentId: string;
    /**
     * 返品対象のパフォーマンスID
     */
    performanceId: string;
    /**
     * 返品対象の注文クライアントID
     */
    clientIds: string[];
    /**
     * 注文返品取引確定後アクション
     */
    potentialActions?: cinerino.transaction.returnOrder.IPotentialActionsParams;
}

export interface IAttributes extends cinerino.task.IAttributes<TaskName.ReturnOrdersByPerformance> {
    data: IData;
}

export type ITask = IExtendId<IAttributes>;
