/**
 * メール送信タスクファクトリー
 * @namespace task.sendEmailNotification
 */

import { IExtendId } from '../autoGenerated';
import * as EmailMessageFactory from '../creativeWork/message/email';
import * as TaskFactory from '../task';
import * as TaskExecutionResult from '../taskExecutionResult';
import TaskName from '../taskName';
import TaskStatus from '../taskStatus';

export interface IData {
    /**
     * 取引ID
     * この値があれば、後で取引から参照できる
     */
    transactionId?: string;
    /**
     * Eメールメッセージ
     */
    emailMessage: EmailMessageFactory.ICreativeWork;
}

export interface IAttributes extends TaskFactory.IAttributes {
    data: IData;
}

export type ITask = IExtendId<IAttributes>;

export function createAttributes(params: {
    status: TaskStatus;
    runsAt: Date;
    remainingNumberOfTries: number;
    lastTriedAt: Date | null;
    numberOfTried: number;
    executionResults: TaskExecutionResult.ITaskExecutionResult[];
    data: IData;
}): IAttributes {
    return TaskFactory.createAttributes({ ...params, ...{ name: TaskName.SendEmailNotification } });
}
