import * as cinerino from '@cinerino/factory';

import { IExtendId } from '../autoGenerated';
import TaskName from '../taskName';

export interface IData {
    /**
     * 取引ID
     * この値があれば、後で取引から参照できる
     */
    transactionId?: string;
    /**
     * Eメールメッセージ
     */
    emailMessage: cinerino.creativeWork.message.email.ICreativeWork;
}

export interface IAttributes extends cinerino.task.IAttributes<TaskName.SendEmailNotification> {
    data: IData;
}

export type ITask = IExtendId<IAttributes>;
