import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

export interface IData {
    transactionId: string;
}

export interface IAttributes extends TaskFactory.IAttributes<TaskName.SettleSeatReservation> {
    data: IData;
}

export type ITask = IExtendId<IAttributes>;
