import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

export interface IData {
    /**
     * Webhook URL
     */
    url: string;
    /**
     * POSTリクエストボディ
     */
    payload: any;
}
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.TriggerWebhook;
    data: IData;
}
/**
 * ウェブフックタスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
