import { IExtendId } from '../autoGenerated';
import { IReservation } from '../reservation/event';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

export interface IData {
    reservation: IReservation;
}

export interface IAttributes extends TaskFactory.IAttributes<TaskName.UpdateOrderReportByReservation> {
    data: IData;
}

/**
 * 予約から注文レポート更新タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
