import * as cinerino from '@cinerino/factory';

import { IExtendId } from '../autoGenerated';
import { IReservation } from '../reservation/event';
import TaskName from '../taskName';

export interface IData {
    reservation: IReservation;
}

export interface IAttributes extends cinerino.task.IAttributes<TaskName.UpdateOrderReportByReservation> {
    data: IData;
}

/**
 * 予約から注文レポート更新タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
