import { actionType, organizationType, personType } from '@cinerino/factory';

import { IExtendId } from './autoGenerated';

/**
 * アクションへの関係者インターフェース
 * 関係者を表現する最低限のインターフェース
 * 継承先にて、インターフェースが強化される可能性あり
 */
export interface IParticipant {
    typeOf: organizationType | personType;
    id: string;
}

/**
 * アクションステータス
 */
export enum ActionStatusType {
    ActiveActionStatus = 'ActiveActionStatus',
    CompletedActionStatus = 'CompletedActionStatus',
    FailedActionStatus = 'FailedActionStatus',
    PotentialActionStatus = 'PotentialActionStatus',
    CanceledActionStatus = 'CanceledActionStatus'
}

/**
 * アクション属性
 */
export interface IAttributes {
    typeOf: actionType;
    actionStatus: ActionStatusType;
    agent?: IParticipant;
    recipient?: IParticipant;
    result?: any;
    error?: any;
    object?: any;
    startDate?: Date;
    endDate?: Date;
}

export type IAction = IExtendId<IAttributes>;
