import { action, actionStatusType, actionType, project } from '@cinerino/factory';

import { IExtendId } from './autoGenerated';

export import IParticipant = action.IParticipant;
export import ActionStatusType = actionStatusType;

/**
 * アクション属性
 */
export interface IAttributes {
    project?: project.IProject;
    typeOf: actionType;
    actionStatus: ActionStatusType;
    agent?: IParticipant;
    recipient?: IParticipant;
    result?: any;
    error?: any;
    object?: any;
    startDate?: Date;
    endDate?: Date;
}

export type IAction = IExtendId<IAttributes>;
