import * as cinerino from '@cinerino/factory';

import { IExtendId } from './autoGenerated';

export type ITransaction = IExtendId<IAttributes>;

/**
 * transaction interface
 * 取引インターフェース
 */
export interface IAttributes {
    project?: cinerino.project.IProject;
    /**
     * 取引タイプ
     */
    typeOf: cinerino.transactionType;
    /**
     * 取引状態
     */
    status: cinerino.transactionStatusType;
    /**
     * 取引主体
     */
    agent: any;
    /**
     * 取引結果
     */
    result?: any;
    /**
     * 取引エラー
     */
    error?: any;
    /**
     * 取引対象
     */
    object?: any;
    /**
     * 取引進行期限
     */
    expires: Date;
    /**
     * 取引開始日時
     */
    startDate?: Date;
    /**
     * 取引終了日時
     */
    endDate?: Date;
    /**
     * タスクエクスポート日時
     */
    tasksExportedAt?: Date;
    /**
     * タスクエクスポート状態
     */
    tasksExportationStatus: cinerino.transactionTasksExportationStatus;
}
