import * as cinerino from '@cinerino/factory';

import * as GMO from '@motionpicture/gmo-service';

import * as ActionFactory from '../../action';
import { IExtendId } from '../../autoGenerated';
import PaymentMethodType from '../../paymentMethodType';

export import IPurpose = cinerino.action.authorize.paymentMethod.any.IPurpose;

/**
 * クレジットカード決済承認アクションオブジェクトインターフェース
 */
export interface IObject extends cinerino.action.authorize.paymentMethod.any.IObject<any> {
    typeOf: PaymentMethodType.CreditCard;
    orderId: string;
    method: GMO.utils.util.Method;
}

export interface IResult extends cinerino.action.authorize.paymentMethod.creditCard.IResult {
    price: number;
}

/**
 * クレジットカード決済承認アクションインターフェース
 */
export interface IAttributes extends ActionFactory.IAttributes {
    purpose: IPurpose;
    agent: ActionFactory.IParticipant;
    recipient: ActionFactory.IParticipant;
    result?: IResult;
    error?: any;
    object: IObject;
    startDate: Date;
    endDate?: Date;
}

export type IAction = IExtendId<IAttributes>;
